baseURL = "https://mzegar.github.io/"
languageCode = "en-us"
title = "s&box TTT"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.highlight]
            style = 'monokai'

[menu]
    [[menu.main]]
        name = "Devblogs"
        url = "/devblogs/"
        weight = 1